title: Gabriel Soyer
description:  Land Systems for Sustainability Lab. Posdoctoral Researcher, Earth & Life Institute, UCLouvain, Belgium. PhD, Political Science & International Affairs, University of Georgia · Comparative Politics · Political Economy · Environment
theme: minima
markdown: kramdown
permalink: pretty

# Simple top nav
header_pages:
  - about.md
  - publications.md
  - teaching.md
